M48
; DRILL file {KiCad 7.0.2} date Sun Oct  1 22:33:33 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-01T22:33:33-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X3.4454Y-6.5807
X3.4493Y-1.2835
T2
X3.4454Y-6.2815
X3.4493Y-1.5827
T0
M30
